magicwagondata=[["Pink Ribbon Hairband","On Sale",0,5],
["Blue Ribbon Hairband","On Sale",0,5],
["Red Ribbon Hairband","On Sale",0,5],
["Blue Pajama Hat","On Sale",0,5],
["Red Frill Pajama Hat","On Sale",0,5],
["Blue Polka-Dot Pajama Top","On Sale",0,5],
["Red Polka-dot Pajama Top","On Sale",0,5],
["Blue Polka-Dot Pajama Pants","On Sale",0,5],
["Red Polka-Dot Pajama Pants","On Sale",0,5],
["Old School Blazer","On Sale",0,5],
["Old School Uniform Top","On Sale",0,5],
["Old School Uniform Pants","On Sale",0,5],
["Old School Uniform (Skirt)","On Sale",0,5],
["Chick Slippers","On Sale",0,75],
["Penguin Slippers","On Sale",0,75],
["Slime Slippers","On Sale",0,75],
["Kawaii Kitty Shoes","On Sale",0,75],
["Scissor Stick","On Sale",0,75],
["Rock Stick","On Sale",0,75],
["Paper Stick","On Sale",0,75],
["Premium Pet Food (6)","On Sale",0,5],
["Sorry! (90 days)","Returning",0,6],
["Friends Plz (90 days)","Returning",0,6],
["Party Plz (90 days)","Returning",0,6],
["Heart Megaphone (90 days)","Returning",0,5],
["Fortunate Megaphone (90 days)","Returning",0,5],
["Premium Water of Life","On Sale",1,35],
["Pet Name Tag","On Sale",1,5],
["Pet Snack","On Sale",1,5],
["Auto HP Potion Skill","On Sale",1,5],
["Expanded Auto Move Skill","On Sale",1,5],
["Auto Move Skill","On Sale",1,5],
["Expired Pickup Skill","On Sale",1,5],
["Ignore Item Skill","On Sale",1,5],
["Auto MP Potion Skill","On Sale",1,5],
["Auto Buff Skill","On Sale",1,5],
["Auto Feed and Movement Skill","On Sale",1,5],
["Auto All Cure Skill","On Sale",1,5],
["One-Time Cosmetic Lens","On Sale",1,4],
["Skin Coupon","On Sale",1,4],
["Hair Color Coupon (REG)","On Sale",1,4],
["Hair Color Coupon (VIP)","On Sale",1,4],
["White Label Ring","On Sale",1,35],
["White Cloud Quote Ring","On Sale",1,35],
["Blizzard Stick","On Sale",1,35],
["Mint Snow Cap","Returning",1,5],
["Cherry Snow Cap","Returning",1,5],
["Mint Snow Outfit","Returning",1,5],
["Cherry Snow Outfit","Returning",1,5],
["Bomber Jacket","On Sale",10,5],
["Pink Pluto T","On Sale",10,5],
["Cherry Layered T","On Sale",10,5],
["Layered Denim Pants","On Sale",10,5],
["Pink-Lined Shorts","On Sale",10,5],
["Starry Sky Blue Beanie","On Sale",10,5],
["Sky Blue Goggled Beanie","On Sale",10,5],
["Khaki Goggled Beanie","On Sale",10,5],
["Lost Baby Chick","On Sale",10,5],
["Bandage Strip","On Sale",10,5],
["Black Hooded Vest","On Sale",10,5],
["Pink Hooded Vest","On Sale",10,5],
["Short Denim Jacket","On Sale",10,5],
["Preppy Black Vest","On Sale",10,5],
["Layered Duckie T","On Sale",10,5],
["Baby Chick Apron","On Sale",10,5],
["Rising Star Baggy Digs","On Sale",10,5],
["Olive Pumpkin Pants","On Sale",10,5],
["Pink Polka-Dotted Boots","On Sale",10,5],
["Pink Wings","On Sale",10,5],
["Dragonfly Wings","On Sale",10,5],
["Sunfire Wings","On Sale",10,5],
["Rainbow Scarf","On Sale",10,5],
["Kitty Parachute","On Sale",10,5],
["Snowflake Scarf","On Sale",10,5],
["Equalizer Scarf","On Sale",10,5],
["Angelic Feathers","On Sale",10,5],
["Pink Angel Stick","On Sale",10,5],
["Shooting Star","On Sale",10,5],
["Shooting Hearts","On Sale",10,5],
["Pink Ribbon Umbrella","On Sale",10,5],
["Broken Sword","On Sale",10,5],
["Egg Throwing Star","On Sale",10,5],
["Strawberry Macaroon Hairpin","Returning",10,25],
["Macaroon Hairpin","Returning",10,25],
["Strawberry Cupcake Hairpin","Returning",10,25],
["Melon Cupcake Hairpin","Returning",10,25],
["Chocolate Cupcake Hairpin","Returning",10,25],
["Parfait Cupcake Hairpin","Returning",10,25],
["Mini Dawn Warrior","Returning",10,25],
["Mini Blaze Wizard","Returning",10,25],
["Mini Wind Archer","Returning",10,25],
["Mini Night Walker","Returning",10,25],
["Mini Thunder Breaker","Returning",10,25],
["Sheep Label Ring","Returning",10,25],
["Sheep Word Bubble Ring","Returning",10,25],
["Buff Freezer (1)","Free",10,15],
["Traveling Merchant (1-day)","Free",10,25],
["Snowman Transformation","Free",10,25],
["Dandelion Puff Mount (90 Day) Coupon","Free",10,25],
["Yeti Mount (90 Day)","Free",20,5],
["Friend Mount (90 Day) Coupon","Free",20,5],
["Solo Ring","On Sale",20,5],
["Heart-Shaped Chocolate","On Sale",20,5],
["Super Megaphone (5)","On Sale",20,5],
["Gachapon Ticket (11)","On Sale",20,5],
["Premium Surprise Style Box (11)","On Sale",20,5],
["Broken Egg Hat","Returning",20,75],
["Egg Outfit","Returning",20,75],
["Chick Shoes","Returning",20,75],
["Chick Gloves","Returning",20,75],
["Chunky Cable-Knit Hat","Returning",20,75],
["Chunky Cable-Knit Top","Returning",20,75],
["Chunky Cable-Knit Bottoms","Returning",20,75],
["Chunky Cable-Knit Shoes","Returning",20,75],
["Gold Fur-Lined Jacket","Returning",20,75],
["Cygnus's Guard","Returning",20,75],
["Universal Transparent Weapon","Returning",20,5],
["Transparent Claw","Returning",20,5],
["Transparent Knuckle","Returning",20,5],
["Transparent Wand","Returning",20,5],
["Transparent Shield","Returning",20,5],
["Transparent Katara","Returning",20,5],
["Transparent Hat","Returning",20,5],
["Transparent Cape","Returning",20,5],
["Transparent Shoes","Returning",20,5],
["Transparent Gloves","Returning",20,5],
["Transparent Earrings","Returning",20,5],
["Transparent Face Accessory","Returning",20,5],
["Transparent Eye Accessory","Returning",20,5],
["More Beautiful Than Flower","New",20,75],
["Gachapon Ticket","Free",20,5],
["Equip Tab 4 Slot Coupon","Free",20,5],
["Use Tab 4 Slot Coupon","Free",20,5],
["Set-up Tab 4 Slot Coupon","Free",20,5],
["ETC Tab 4 Slot Coupon","Free",20,5],
["Wild Totem Coupon","Free",20,5],
["Horoscope Hat (Aquarius)","Free",20,75],
["Horoscope Hat (Pisces)","Free",20,75],
["Horoscope Hat (Aries)","Free",20,75],
["Horoscope Hat (Taurus)","Free",20,75],
["Horoscope Hat (Gemini)","Free",20,75],
["Horoscope Hat (Cancer)","Free",20,75],
["Horoscope Hat (Leo)","Free",20,75],
["Horoscope Hat (Virgo)","Free",20,75],
["Horoscope Hat (Libra)","Free",20,75],
["Horoscope Hat (Scorpius)","Free",20,75],
["Horoscope Hat (Sagittarius)","Free",20,75],
["Horoscope Hat (Capricorn)","Free",20,75],
["Horoscope Overall","Free",20,75],
["Horoscope Overall","Free",20,75],
["Horoscope Shoes","Free",20,75],
["Horoscope Crossbow","Free",50,75],
["Horoscope Sword","Free",50,75],
["Horoscope Bow","Free",50,75],
["Horoscope Net","Free",50,75],
["Horoscope Claw","Free",50,75],
["Puffram Hat","Returning",50,75],
["Puffram Onesie","Returning",50,75],
["Puffram Gloves","Returning",50,75],
["Puffram Shoes","Returning",50,75],
["Cotton Candy Cloud","Returning",50,75],
["Photo-op","Returning",50,5],
["Customized Soul Enchanter","Free",50,13],
["Ombra & Luce Sabre","Free",50,13],
["Bloody Ruby Sabre","Free",50,13],
["Heaven's Seraphim","Free",50,13],
["Dynamic Seraphim","Free",50,13],
["5K Maple Points","Free",50,3],
["Themed Surprise Style Box (3)","Returning",100,75],
["Summer Surprise Style Box (3)","Returning",100,75],
["Valentine Surprise Style Box (3)","Returning",100,75],
["Adventure Surprise Style Box (3)","Returning",100,75],
["Rise Surprise Style Box (3)","Returning",100,75],
["Puppy Love Samurai Hat (M)","Returning",100,75],
["Puppy Love Samurai Outfit (M)","Returning",100,75],
["Puppy Love Samurai Shoes (M)","Returning",100,75],
["Puppy Love Samurai Tail (M)","Returning",100,75],
["Puppy Love Samurai Hat (F)","Returning",100,75],
["Puppy Love Samurai Outfit (F)","Returning",100,75],
["Puppy Love Samurai Shoes (F)","Returning",100,75],
["Puppy Love Samurai Tail (F)","Returning",100,75],
["Pilot Cap","Returning",100,75],
["Pilot Suit","Returning",100,75],
["Aerial Wave Cape","Returning",100,75],
["Pilot Boots","Returning",100,75],
["The Jackal","Returning",100,75],
["Star Orchid","Returning",100,3],
["Star Lotus","Returning",100,3],
["Star Phantom","Returning",100,3],
["20 Slot Herb Bag","Free",100,1],
["20 Slot Mineral Bag","Free",100,1],
["20 Slot Production Bag","Free",100,1],
["20 Slot Chair Bag","Free",100,1],
["20 Slot Soul Bag","Free",100,1],
["Zero Android Coupon","Free",100,3],
["Epic Lulz Damage Skin","Free",100,3],
["Sleepy Kitty","New",100,2],
["Sleepy Bunny","New",100,2],
["Drowsy Rabbit Damage Skin","New",100,2],
["Winter Bunny Hat (Teal)","Returning",150,3],
["Winter Bunny Hat (Pink)","Returning",150,3],
["Winter Bunny Coat (Teal)","Returning",150,3],
["Winter Bunny Coat (Pink)","Returning",150,3],
["Winter Bunny","Returning",150,3],
["Sweet Dreams","New",150,3],
["Sleep Tight","New",150,3],
["Puppy Cushion","New",150,3],
["Onyx Apple (10)","Free",150,15],
["30K Maple Point Coupon","Free",200,2],
["Dreamland","New",200,2],
["Dreamy Glow","New",200,2],
["Ruby Snow Hat","New",200,2],
["Emerald Snow Hat","New",200,2],
["Ruby Snow Outfit","New",200,2],
["Emerald Snow Outfit","New",200,2],
["Ruby Snow Shoes","New",200,2],
["Emerald Snow Shoes","New",200,2],
["Bedazzle","New",200,2],
["Snow Crystal Wand","New",200,2],
["Pure White Bunny Label Ring","New",200,2],
["Pure White Bunny Chat Ring","New",200,2],
["Snow Crystal Scene","New",200,2],
["Permanent Ice Skating Mount","New",200,2]]

magicwagondata_old=[["\"A\" Cap","On Sale",0,51],
["Amethyst Eye Color","On Sale",0,34],
["Aqua Road T","On Sale",0,51],
["Aqua Seraphim","On Sale",0,51],
["Auto All Cure Skill","On Sale",0,34],
["Auto Buff Skill","On Sale",0,34],
["Auto Feed and Movement Skill","On Sale",0,34],
["Auto HP Potion Skill","On Sale",0,34],
["Auto Move Skill","On Sale",0,34],
["Auto MP Potion Skill","On Sale",0,34],
["Black Crown","On Sale",0,51],
["Black Eye Color","On Sale",0,34],
["Black Skull Eye Patch","On Sale",0,51],
["Black-lace Ribbon","On Sale",0,51],
["Blizzard Stick","On Sale",0,51],
["Blue Eye Color","On Sale",0,34],
["Blue Nymph Wing","On Sale",0,51],
["Cowboy Shorts","On Sale",0,51],
["Devil Horns","On Sale",0,51],
["Expanded Auto Move Skill","On Sale",0,34],
["Expired Pickup Skill","On Sale",0,34],
["Fallen Angel Headband","On Sale",0,51],
["Fallen Angel Tail","On Sale",0,51],
["Fallen Angel Wings","On Sale",0,51],
["Fluttering Sunhat","On Sale",0,51],
["Green Eye Color","On Sale",0,34],
["Green Nymph Wing","On Sale",0,51],
["Hazel Eye Color","On Sale",0,34],
["Ignore Item Skill","On Sale",0,34],
["Lollipop","On Sale",0,51],
["Metal Shades","On Sale",0,51],
["Pet Name Tag","On Sale",0,34],
["Pet Snack","On Sale",0,34],
["Premium Water of Life","On Sale",0,34],
["Rabbit Ear Hood","On Sale",0,51],
["Red Eye Color","On Sale",0,34],
["Rolled-up Skinny Jeans","On Sale",0,51],
["Sapphire Eye Color","On Sale",0,34],
["Star Hair Pin","On Sale",0,51],
["Striped Hoodie Shirt","On Sale",0,51],
["Superstar Headphones","On Sale",0,51],
["Urban Pirate Outfit","On Sale",0,51],
["Victory Hairpin","On Sale",0,51],
["Violet Eye Color","On Sale",0,34],
["White Basic Cap","On Sale",0,51],
["White Cloud Quote Ring","On Sale",0,51],
["White Eye Color","On Sale",0,34],
["White Label Ring","On Sale",0,51],
["Yellow Nymph Wing","On Sale",0,51],
["Casual Cowboy Hat","Returning",1,17],
["Cool Carrot Hat","Returning",1,17],
["Globe Cap","Returning",1,17],
["Heart Key","Returning",1,17],
["Psyche Flora","Returning",1,17],
["Psyche Melody","Returning",1,17],
["Psyche Mystic","Returning",1,17],
["Round-We-Go Mirror Ball","Returning",1,17],
["Tania Sword","Returning",1,17],
["Warm Carrot Hat","Returning",1,17],
["Bell Mini Flower Pin","Returning",10,17],
["Black Hit Me Shirt","On Sale",10,34],
["Blazing Sword","On Sale",10,34],
["Blue Kitty Hood","On Sale",10,34],
["Braided Mini Flower Pin","Returning",10,17],
["Brown Checkered Pants","On Sale",10,34],
["Buff Freezer (5)","Free",10,24],
["Colorful Rainbow","Free",10,17],
["Cow Mask","On Sale",10,34],
["Dark Seraphim","On Sale",10,34],
["Demon Sickle","On Sale",10,34],
["Denim Overalls","On Sale",10,34],
["Dollish Pink","On Sale",10,34],
["Eclipse Bird Mount (90 Day) Coupon","Free",10,17],
["Gachapon Ticket (11)","On Sale",10,34],
["Ghost Weapon","On Sale",10,34],
["Hamster Baller Mount (90 Day) Coupon","Free",10,17],
["Headphone Bandana","On Sale",10,34],
["Heart-Shaped Chocolate","On Sale",10,34],
["Hooded Track Suit","On Sale",10,34],
["Ice Cold Red","On Sale",10,34],
["Janus Sword","On Sale",10,34],
["Khaki Goggled Beanie","On Sale",10,34],
["Kitty Hoodie","On Sale",10,34],
["Maple MSX Guitar","On Sale",10,34],
["Mercury Sword","Returning",10,17],
["Mini Blaze Wizard","Returning",10,17],
["Mini Dawn Warrior","Returning",10,17],
["Mini Mini Flower Pin","Returning",10,17],
["Mini Night Walker","Returning",10,17],
["Mini Thunder Breaker","Returning",10,17],
["Mini Wind Archer","Returning",10,17],
["Musical Violin","On Sale",10,34],
["My Buddy Whale","On Sale",10,34],
["Olive Beanie","On Sale",10,34],
["Orange Mushroom Balloon","On Sale",10,34],
["Pink wing bag","On Sale",10,34],
["Politician Glasses","On Sale",10,34],
["Premium Surprise Style Box (11)","On Sale",10,34],
["Preppy Blue Shirt","On Sale",10,34],
["Rainbow Brush","On Sale",10,34],
["Return of Angel Wing","Free",10,17],
["Rose Mini Flower Pin","Returning",10,17],
["Sachiel Sword","On Sale",10,34],
["Seal Pillow","On Sale",10,34],
["Shadow Style","Free",10,17],
["Shock Wave","On Sale",10,34],
["Sky Blue Goggled Beanie","On Sale",10,34],
["Solo Ring","On Sale",10,34],
["Sprite Wings","Free",10,17],
["Starry Night Cloud Mount (90 Day) Coupon","Free",10,17],
["Starry Sky Blue Beanie","On Sale",10,34],
["Super Megaphone (5)","On Sale",10,34],
["Underpants","On Sale",10,34],
["Veamoth Sword","On Sale",10,34],
["Vintage Glasses","On Sale",10,34],
["White Beanie","On Sale",10,34],
["Wildflower Mini Flower Pin","Returning",10,17],
["Wind Breaker Mount (90 Day) Coupon","Free",10,17],
["Wriggling Mount (90 Day) Coupon","Free",10,17],
["Azure Sun Cap","Returning",20,68],
["Banana Headphone Hat","Returning",20,68],
["Brown Puppy Shoes","Returning",20,68],
["Brown Teddy Capris Pants","Returning",20,68],
["Brown Teddy Top","Returning",20,68],
["Diamond Veil","Returning",20,68],
["Equip Tab 4 Slot Coupon","Free",20,17],
["ETC Tab 4 Slot Coupon","Free",20,17],
["Gachapon Ticket","Free",20,17],
["Green Polo","Returning",20,68],
["Horoscope Bow","Free",20,51],
["Horoscope Claw","Free",20,51],
["Horoscope Crossbow","Free",20,51],
["Horoscope Hat (Aquarius)","Free",20,51],
["Horoscope Hat (Aries)","Free",20,51],
["Horoscope Hat (Cancer)","Free",20,51],
["Horoscope Hat (Capricorn)","Free",20,51],
["Horoscope Hat (Gemini)","Free",20,51],
["Horoscope Hat (Leo)","Free",20,51],
["Horoscope Hat (Libra)","Free",20,51],
["Horoscope Hat (Pisces)","Free",20,51],
["Horoscope Hat (Sagittarius)","Free",20,51],
["Horoscope Hat (Scorpius)","Free",20,51],
["Horoscope Hat (Taurus)","Free",20,51],
["Horoscope Hat (Virgo)","Free",20,51],
["Horoscope Net","Free",20,51],
["Horoscope Overall (M)","Free",20,51],
["Horoscope Overall (F)","Free",20,51],
["Horoscope Shoes","Free",20,51],
["Horoscope Sword","Free",20,51],
["Jam Chat Ring","Returning",20,68],
["Jam Label Ring","Returning",20,68],
["Otherworldly Slacks","Returning",20,68],
["Owl Hat","Returning",20,68],
["Phoenix Wing Cape","Returning",20,68],
["Pimp Stick","Returning",20,68],
["Pink Kitty Blue Sneakers","Returning",20,68],
["Pink Kitty Denim Skirt","Returning",20,68],
["Puffy Ram Hat","Returning",20,68],
["Rabbit and Bear Book Bag","Returning",20,68],
["Rabbit and Bear Flashlight","Returning",20,68],
["Rabbit and Bear Hat","Returning",20,68],
["Rabbit and Bear Shirt","Returning",20,68],
["Rabbit Ear Dress","Returning",20,68],
["Set-up Tab 4 Slot Coupon","Free",20,17],
["Strawberry Headphone Hat","Returning",20,68],
["Transparent Cape","Returning",20,51],
["Transparent Claw","Returning",20,51],
["Transparent Earrings","Returning",20,51],
["Transparent Eye Accessory","Returning",20,51],
["Transparent Face Accessory","Returning",20,51],
["Transparent Gloves","Returning",20,51],
["Transparent Hat","Returning",20,51],
["Transparent Katara","Returning",20,51],
["Transparent Knuckle","Returning",20,51],
["Transparent Shield","Returning",20,51],
["Transparent Shoes","Returning",20,51],
["Transparent Wand","Returning",20,51],
["Universal Transparent Weapon","Returning",20,51],
["Use Tab 4 Slot Coupon","Free",20,17],
["Villain Gloves","Returning",20,68],
["Villain Shoes","Returning",20,68],
["Villain's Cool Tights (Outfit)","Returning",20,68],
["Villain's Mask (Hat)","Returning",20,68],
["Watermelon Headphone Hat","Returning",20,68],
["White Kitty Pink Top","Returning",20,68],
["Wild Totem Coupon","Free",20,17],
["5K Maple Point Coupon*","Free",50,17],
["Bloody Ruby Sabre","Free",50,34],
["Candy Party Ribbon","Free",50,51],
["Cat in a Hat","Returning",50,68],
["Dynamic Seraphim","Free",50,34],
["Heart Fur Coat","Free",50,51],
["Heaven's Seraphim","Free",50,34],
["Kitty Follower","Returning",50,68],
["Kitty Overall (Male)","Returning",50,68],
["Ombra & Luce Sabre","Free",50,34],
["Paw Gloves","Returning",50,68],
["Red Check Rider","Returning",50,68],
["Shark Bite Shoes","Returning",50,68],
["Shark Bodysuit","Returning",50,68],
["Shark Cape","Returning",50,68],
["Shark Hoodie","Returning",50,68],
["Strawberry Fitness Jump Rope","Free",50,34],
["Strawberry Hairpin","Free",50,34],
["Strawberry Sneakers","Free",50,34],
["Strawberry Training Pants","Free",50,34],
["Strawberry Training Shirt","Free",50,34],
["Windy Paw Scarf","Returning",50,68],
["Winged Kitty Dress (Female)","Returning",50,68],
["20 Slot Chair Bag","Free",100,27],
["20 Slot Herb Bag","Free",100,27],
["20 Slot Mineral Bag","Free",100,27],
["20 Slot Production Bag","Free",100,27],
["20 Slot Soul Bag","Free",100,27],
["Adventure Surprise Style Box (3)","Returning",100,51],
["Anniversary Surprise Style Box (3)","Returning",100,51],
["Cat Hood","Free",100,17],
["Cat Lolita Cape","Free",100,27],
["Cat Lolita Gloves","Free",100,27],
["Cat Lolita Hat","Free",100,27],
["Cat Lolita Outfit","Free",100,27],
["Cat Lolita Shoes","Free",100,27],
["Cloud Ship Constellation Chair","Free",100,17],
["Dangerous Medicine Bottle","Free",100,17],
["Feline Blue Sleeves","Free",100,17],
["Feline Wishes Star Chair","Free",100,17],
["Innocent Outfit","Free",100,17],
["Lily Bucket Hat","New",100,17],
["Marine Stripe Umbrella","Free",100,27],
["Nero Bucket Hat","New",100,17],
["Otherworldly Tour Bus Chair","Free",100,17],
["Permanent Rainbow Swing Mount Coupon","New",100,17],
["Permanent Teatime Bunny Mount Coupon","Free",100,17],
["Pink Bean Costume Chair","Free",100,17],
["Rise Surprise Style Box (3)","Returning",100,51],
["Rock Spirit (Perm)","Returning",100,17],
["Small Spirit (Perm)","Returning",100,17],
["Summer Surprise Style Box (3)","Returning",100,51],
["Tree Spirit (Perm)","Returning",100,17],
["Valentine Surprise Style Box (3)","Returning",100,51],
["Candybear Watch","Free",150,17],
["Lily Print Overfit Outfit","New",150,17],
["Mustachio on a Stick","Free",150,17],
["Mustachioed Ballcap","Free",150,17],
["Mustachioed Bowler","Free",150,17],
["Nero Print Overfit Outfit","New",150,17],
["Pupmallow Pop Weapon","New",150,17],
["Snazzy Bunny Outfit","Free",150,17],
["Spaceyman","Free",150,17],
["Spaceywoman","Free",150,17],
["30K Maple Point Coupon*","Free",200,14],
["Dewy Four-Leaf Clover Group Chair","New",200,14],
["Dreamy Unicorn Chair","New",200,14],
["Permanent Plush Bunny Mount Coupon","New",200,14],
["Starry Summer Night Hat","New",200,14],
["Starry Summer Night Outfit (F)","New",200,14],
["Starry Summer Night Outfit (M)","New",200,14],
["Starry Summer Night Shoes","New",200,14],
["Starry Summer Night Weapon","New",200,14]]